name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # Create Release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## 🚀 What's New
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## 📦 Docker Images
            
            - Backend: `ghcr.io/${{ github.repository }}-backend:${{ github.ref_name }}`
            - Frontend: `ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}`
            
            ## 🔧 Installation
            
            ```bash
            docker-compose pull
            docker-compose up -d
            ```
          draft: false
          prerelease: false

  # Build and Upload Assets
  build-assets:
    name: Build Release Assets
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      
      - name: Create release archive
        run: |
          tar -czf frontend-build-${{ github.ref_name }}.tar.gz -C frontend/build .
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./frontend-build-${{ github.ref_name }}.tar.gz
          asset_name: frontend-build-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
